### PR TITLE
Add tooltips

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
This is the first step to add tooltips to the REPL. In Fable, I just [exposed the `getToolTipAtLocation` function](https://github.com/fable-compiler/Fable/commit/5c323b3e4a4e513414f50854f85bc06a1fbe197b) @ncave added some time ago, and here I'm just registering the hover provider. However, the only result I get from `FableREPL.GetToolTipText` is:

```
internal error: empty list Parameter name: l
```

So I'm afraid I'll need some @ncave magic again here, any ideas?

Happy New Year btw :wink:

### CODE REVIEW

**Comment by ncave** [comment]
@alfonsogarciacaro Happy New Year to you too!
I think you need to pass the identifier on which you're hovering, like [here](https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete.Core/CompilerServiceInterface.fs#L87-L93). Perhaps Monaco can provide the identifier, instead of using the lexer lookup from FSAC, but I have not looked if that's readily available.
Also, there seems to be some tooltip caching in `GetToolTipText` (key [here](https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/service.fs#L1042)), so if that doesn't perform well or is eating too much memory it can be reworked.

**Comment by alfonsogarciacaro** [comment]
Awesome, tooltips are working now! :tada: :tada: Thanks a lot @ncave! :clap: :clap:

This is ready to merge 😄

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime The only thing that's missing now to replace the old REPL should be putting the F# code in the URL so people can share it, right? I guess we need to do the same with the HTML code.

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime Also, I'm getting this error in the Browser console always when loading the REPL. I think it comes from Thot:

```
Decode.fs:288 Uncaught Error: Expecting an object with a field named `type` but instead got:
{
    "source": "react-devtools-detector",
    "reactBuildType": "development"
}
    at andThen (Decode.fs:288)
    at Mouse.fs:43
    at args3 (Generator.fs:22)
    at curriedFn (Generator.fs:11)
    at Mouse.fs:62
```

**Comment by MangelMaxime** [comment]
Yes that's right.
We need to use the urlParser for that.

**Pull request merged**
