### PR TITLE
Use artifact from AppVeyor

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
Ok, after some head scratching I got this working (more or less). Great job @MangelMaxime! I haven't modified the build script much but to test this you can:

- Run `sh build.sh DownloadReplArtifact` to download the REPL from AppVeyor's build
- Run `yarn run build-app` (or watch-app) to compile the Fable projects
- Run `yarn start` to start the local server

Compilation, error highlighting and autocompletion is working. But there are still a few parts missing:

- I cannot use `Fable.Import.Browser`, I've tried several things (using net45 assemblies, regenerating the metadata with FCS_export) but whenever any member from it is called the editor highlights it (see capture) and I see the message `internal error: Cannot read property 'compilingFslib' of undefined (Failure)` when hovering the mouse. Any idea of the cause/solution to this problem @ncave?
- I don't understand what is `localhost:8080` in [these lines](https://github.com/fable-compiler/fable-repl/blob/1cf616b3ac68007372e3f3b1b1eb760d7af0e718/src/App/Generator.fs#L10-L14) for. I'm not sure if I'm doing it well, but in any case I guess we won't be able to access `localhost` if we post the REPL online.

Please have a look and tell me if you know how can we move forward from here :+1:

screen shot 2017-12-03 at 6 04 06 pm

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Thanks for the PR I will review/test it locally tomorrow.

I believe we should be able to remove the [`watch-app`](https://github.com/fable-compiler/fable-repl/blob/b648be5069bec53449d5bd3fc2755c07bd0799aa/package.json#L12) scripts because you can use directly [`start-app`](https://github.com/fable-compiler/fable-repl/blob/b648be5069bec53449d5bd3fc2755c07bd0799aa/package.json#L13) to use the webpack-dev-server.

Don't touch my beautiful `localhost:8080` lines :smiling_imp: 

No more seriously, I will make the `host` auto-discover before making the REPL online (I will add a TODO in the right PR). Basically the `generator.fs` is used to generate Blob files which are then passed to the iframe. This allow, us to serve the Html + JavaScript for the iframe without having a backend server hosting temp files etc.

**Comment by alfonsogarciacaro** [comment]
Sorry, @ncave, any idea why the `Fable.Import.Browser.dll` reference is not working? Unfortunately this prevents using the REPL to interact with canvas or any other HTML element.

**Comment by ncave** [comment]
@alfonsogarciacaro Looks ok to me, it works [here](https://github.com/ncave/FSharp.Compiler.Service/blob/fable/fcs/fcs-fable/test/app.fs#L223-L226). Note: the column pos seems to be zero-based.
Once you publish a version with [this fix](https://github.com/fable-compiler/Fable/pull/1284), it should be fine.

**Comment by alfonsogarciacaro** [comment]
@ncave Would you mind checking out branch `feature/new_repl2` of this repo and running the following?

```
git clean -xfd      # just in case
sh build.sh          # or build.cmd on Windows
yarn start
```

When I try to compile [the canvas sample code](https://raw.githubusercontent.com/fable-compiler/samples-browser/3854509edcaf5c69af611e359f7ef9c08b000daf/src/canvas/App.fs) in the REPL, besides the red squiggles in anything referencing `Fable.Import.Browser` with the message "internal error: Cannot read property 'compilingFslib' of undefined (Failure)" on hovering, this is the result of JS compilation (anything else that doesn't reference Fable.Import.Browser.dll works):

```js
export function init() {
  let canvas;
  throw 1;
  throw 1;
  throw 1;
  let ctx;
  throw 1;
  throw 1;
  throw 1;
  throw 1;
  throw 1;
}
init();
```

**Comment by ncave** [comment]
@alfonsogarciacaro
Not sure about that, as I'm not all that familiar with the Browser bindings.

Changing this line:
`let canvas = Browser.document.getElementsByTagName_canvas().[0]`
with this one:
`let canvas = Browser.document.createElement_canvas()`
makes it work (I know it's not the same, it's just an example).

So not all of `Fable.Import.Browser.dll` is bad, it must be something else.

P.S. There is a minor build issue when building on tabula rasa:
```
   ERROR in ./src/Monaco/util.js
    Module not found: Error: Can't resolve '../../../Fable/src/js/fable-utils/babel-plugins' 
in 'C:\Projects\fable-repl\src\Monaco'
     @ ./src/Monaco/util.js 5:0-80
```
probably needs to be replaced with local reference.

**Comment by alfonsogarciacaro** [comment]
Awesome! It's indeed working if I use your suggestion:

```fsharp
let canvas = Browser.document.createElement_canvas()
Browser.document.body.appendChild(canvas) |> ignore
```

I can even run the [Ozmo game](https://gist.githubusercontent.com/alfonsogarciacaro/faaf0e2e44c84c09450a6bcbe1e68730/raw/ac641f6cfd8a77ee500602251692a2e7c43a2994/ozmo.fs)! :tada: So you're right it must be something else, and it seems the problem is [methods with `Emit` attribute](https://github.com/fable-compiler/fable-import/blob/7bb5576970d1533eb400b5ddcf712c6ed4bf62c0/Browser/Fable.Import.Browser.fs#L1851). Do you know if somehow attribute info is partially missing in the metadata assemblies?

About the build error, I don't remember seeing it but I updated npm dependencies and added `fable-utils` explicitly in case it fixes the error.

BTW @MangelMaxime the problem with the ozmo game is the keyboard events are not captured by the iframe. Is there any solution for this? Would be an option to remove the iframe?

BTW2 @ncave the autocompletion in the REPL is very slow when working on a long piece of code. Is there a way to [parse the code](https://github.com/fable-compiler/fable-repl/blob/07d30e586f410cdf97d361601eade5bdcf97443e/src/Monaco/editor.fs#L99) without generating the AST, as FSAC does?

**Comment by MangelMaxime** [comment]
I will take a look at why the events are not working probably something to do with how iframes work etc. But it's should work for example, the [elm mario debugger sample](http://debug.elm-lang.org/edit/Mario.elm) is using iframe too and they have keyboard support.

Also to test the REPL, I am actually using this [piece of code](https://github.com/fable-compiler/fable-repl/blob/feature/new_repl/src/App/Main.fs#L416-L436) which allow me to not create a canvas directly. Creating a canvas via JS is harder than we think because, the size, ratio etc. need to be set too.

But every any case, we need to fix the `Emit` attributes from DLL if it's the problem.

I will take a look at this PR and when I have publish Thot beta version. Taking longer that I expected but I should do it today.

**Comment by ncave** [comment]
@alfonsogarciacaro 
> Is there a way to parse the code without generating the AST, as FSAC does?

Do you have a link to how FSAC does it, or are you suggesting to not do as FSAC does it?

**Comment by ncave** [comment]
@alfonsogarciacaro
One possible (temporary) solution is to switch to the old metadata binaries until performance on the netcore binaries can be improved (there is a bottleneck somewhere that needs to be profiled, see [#1205](https://github.com/fable-compiler/Fable/issues/1205)).

**Comment by ncave** [comment]
@alfonsogarciacaro 
> ... it seems the problem is methods with Emit attribute...

No, that's when it shows, but is actually caused by [#1291](https://github.com/fable-compiler/Fable/issues/1291).

**Comment by alfonsogarciacaro** [comment]
@ncave 

> Do you have a link to how FSAC does it, or are you suggesting to not do as FSAC does it?

AFAIK, to get the AST you need to [set `keepAssemblyContents` to true](https://github.com/fable-compiler/Fable/blob/433e43ba585c40302c64227be348446971804484/src/dotnet/dotnet-fable/StateUtil.fs#L266) so I assume FSAC is just not setting it. But I don't see such an option with [the InteractiveChecker](https://github.com/fable-compiler/Fable/blob/433e43ba585c40302c64227be348446971804484/src/dotnet/Fable.JS/Main.fs#L137).

> One possible (temporary) solution is to switch to the old metadata binaries until performance on the netcore binaries can be improved.

Yes, probably this is better to improve the user experience :+1:

> No, that's when it shows, but is actually caused by #1291.

Awesome, thanks a lot for investigating this! I'll fix the issue 💪

**Comment by MangelMaxime** [comment]
Because this PR, is about adding AppVeyor artifact usage I am merging it. Thank for adding it @alfonsogarciacaro should speed up startup time for people and allow smaller machine to work on this project like my laptop at work :)

I will list the Emit problem inside the #8 PR so we can have all the tasks in one place.

**Comment by ncave** [comment]
@alfonsogarciacaro 
The only place in FSAC I can find that uses FSharpChecker is [here](https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete.Core/CompilerServiceInterface.fs#L295-L298), and it has `keepAssemblyContents = true`.

Regardless, I don't think setting it to false does much besides throwing the AST away after it's generated (it still makes it, it has to). Perhaps you can elaborate a bit more what your optimization idea is.

**Comment by alfonsogarciacaro** [comment]
@ncave Awesome, after fixing [#1291](https://github.com/fable-compiler/Fable/issues/1291) the REPL is working perfectly now, thank you! :clap: :clap: :clap:

About the optimization, I was probably wrong. From the beginning I read in the [FCS tutorial](http://fsharp.github.io/FSharp.Compiler.Service/typedtree.html#Checking-code) that the difference between getting the symbols vs the full AST was setting `keepAssemblyContents = true`, so I just assumed leaving it to false was a way to parse the code faster to only get the symbols. But it seems my assumption was not correct 😅

**Comment by alfonsogarciacaro** [comment]
BTW @StachuDotNet, you should be able to run the REPL now. Clone the `feature/new_repl` branch, run the build script and then `yarn start` :)

**Comment by StachuDotNet** [comment]
@alfonso, :D time for some documentation.

On Dec 12, 2017 5:46 AM, "Alfonso Garcia-Caro" <notifications@github.com>
wrote:

BTW @StachuDotNet <https://github.com/stachudotnet>, you should be able to
run the REPL now. Clone the feature/new_repl branch, run the build script
and then yarn start :)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/fable-compiler/fable-repl/pull/10#issuecomment-351014716>,
or mute the thread

**Comment by ncave** [comment]
@alfonsogarciacaro Awesome, thanks for fixing it.

**Pull request merged**
