### PR TITLE
[WIP][Top Secret] Working on new version of repl

### PR DESCRIPTION
**Pull request by MangelMaxime**
*This PR is top secret nothing to see here :)*

Ok, will stop here my mysterious intro and show you a gif:
 
repl_demo_v2

As you can guess, now the repl is executing the code inside an iframe. Which mean we now have access to the DOM. This is really a WIP and I need to do lot of clean up and also I want to add more features. I mostly wanted to use this PR to share my progress and avoid being two to work on the next REPL version.

I am basing this PR on the #7 to have a better diff. Will try to keep the branch sync and apply the different patch where they belongs. Fixing architecture of the repo goes to #7 where updating the REPL UX goes here.

Only big thing missing to merge #7 is the autocomplete support as it's a regression. The UglifyJS thing can be solve later as it's not blocking.

PS: Yes, I consider using the React-monaco components but it don't feel ready yet and don't allow us enough flexibility. So no need to add it for now :)

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
AMAZING!!! Keep up the awesomeness!

ezgif com-optimize

**Comment by MangelMaxime** [comment]
We now have three editors:
- one for the F# code
- one for the HTML code
- one for the ES2015 output

repl_layout_2

Next steps are:
- [x] Make the editor support resize
  - [x] Resize via the mouse
  - [x] Collapse/Expand editor area
- [ ] Add access to the FCS calss in an Elmish Cmd style. This should improve the UX because we can have more infos like performance of compilation, is it doing something in the background. And also, we will be able to inform the user during the initial loading time.
- [x] Re-add the auto-complete
- [ ] Add export/import support, via the url like we have for the current repl
- [ ] Add support to load samples.
- [ ] Remove the hardcorded [localhost:8080](https://github.com/fable-compiler/fable-repl/blob/1cf616b3ac68007372e3f3b1b1eb760d7af0e718/src/App/Generator.fs#L10-L14) 
- [ ] Fix the Emit attributes as mentions in https://github.com/fable-compiler/fable-repl/pull/10#issuecomment-350215106

*I really need to find another GIF recorder under linux. This one output really large file and also looks likes it's playing speed x2-3...*

**Comment by MangelMaxime** [comment]
Hello guys,

would it be possible for you to test the current state of the REPL in this PR ? You can see the features added in my previous message.

Idea is to get feedback on the resize/collapse, auto-complete, build/run features.

I will later remove the initial state with `No apps compiled yet` or make it have a better display is a little rough in current state.

PS: The REPL is build with the latest master branch of the different repos.

**Comment by StachuDotNet** [comment]
On it :)

**Comment by alfonsogarciacaro** [comment]
This is amazing @MangelMaxime!!! :clap: :clap: :clap:

I gave it a try but I got an error. I don't have SSH installed, maybe https can be used instead? `https://github.com/ncave/FSharp.Compiler.Service.git`

```
Running build with 1 worker
Starting Target: Setup
Can't find FSharp.Compiler.Service_fable at: /Users/alfonsogarciacaronunez/dev/fable-repl/..
Do you want me to setup it for you ? (O/N)
O
Installing FSharp.Compiler.Service_fable for you
git clone git@github.com:ncave/FSharp.Compiler.Service.git FSharp.Compiler.Service_fable
﻿Running build failed.
Error:
System.Exception: Cloning into 'FSharp.Compiler.Service_fable'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

> I love that I have to write `O` for yes ;)

**Comment by MangelMaxime** [comment]
Grr.. I hate https :D

One thing that surprise me is why is it testing your SSH key when the repo are publics.

But if the script can support it why not yes. And yes, it's possible that `O` means `Oui` :D
Also you can also do `./build.sh All setup=auto` to avoid the questions :)

**Comment by alfonsogarciacaro** [comment]
I cloned ncave's FCS manually, checked out `fable` branch and seems to work but I got a StackOverflow exception at the end of the JS compilation. This happened to me before, I'll try on Windows :)

**Comment by MangelMaxime** [comment]
Strange I don't have any SO since I started this PR. Perhaps something new has been added to the latest version of the `fable` branch.

**Comment by StachuDotNet** [comment]
Running into the same issue when executing './build.cmd All setup=auto':
```
C:\Program Files\Git\cmd\git.exe clone git@github.com:ncave/FSharp.Compiler.Service.git FSharp.Compiler.Servi
ce_fable
Running build failed.
Error:
System.Exception: Cloning into 'FSharp.Compiler.Service_fable'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
   at Fake.Git.CommandHelper.gitCommand(String repositoryDir, String command) in D:\code\FAKE\src\app\FakeLib
\Git\CommandHelper.fs:line 67
   at Fake.Git.Repository.clone(String workingDir, String repoUrl, String toPath) in D:\code\FAKE\src\app\Fak
eLib\Git\Repository.fs:line 15
   at FSI_0005.Build.ensureRepoSetup(RepoSetupInfo info)
   at FSI_0005.Build.clo@95.Invoke(Unit _arg1)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\FAKE\src\app\FakeLib\TargetHelper
.fs:line 626

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Setup      Failure
---------------------------------------------------------------------
Status:    Failure
```

**Comment by alfonsogarciacaro** [comment]
After some tries I finally managed to complete the build (on Windows and using Fable development version) but I may be missing something because I get errors when running the REPL 🤔 

image

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro In general, to run the repl I do: `./build.sh Build.FCS` and then ` yarn run start-app` 

This should be enough, when you have the folders already setup. I just upgraded the paket version to use Fable 1.3.4 because a replacement was missing for me.

And indeed, seems like something change on the FCS or Fable side. Probably the FCS side as it's the one related to type checking, etc.

Also, for me Fable is generated the right code and the sample is running fine:
screenshot from 2017-11-29 13-07-14

I edited, the code to force a re-evaluation of the file. Perhaps, @ncave will have more infos about the bugs we have now.

Edit: 

To complete this part:

> And indeed, seems like something change on the FCS or Fable side. Probably the FCS side as it's the one related to type checking, etc.

What's strange is the FCS branch has not changed since my last check and only the Fable repo and Repl repo have new commits in it...

**Comment by MangelMaxime** [comment]
Is the current layout good enough ? Or should I already add support to something like shown in @mike-morr comments ?

**Comment by alfonsogarciacaro** [comment]
I think the layout is great! When we get it working the next step probably is to offer a way to save and share snippets, and later add a file explorer if we support multiple files.

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime I think we should merge this, keep working on master and publish a beta version of the REPL for this repository so people can try it and give feedback. If you still want to be able to keep pushing comments you can be in charge of master and the rest of us use PRs :+1:

BTW, as @ncave suggested I confirmed that the performance when using net45 assemblies is better so maybe we should be using those for now. I'm also planning to move the checker to a worker so it doesn't freeze the UI. I'll send a PR :)

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Yes, we can merge this PR into master directly I think and close #7 too.

And, I will use issues + PR to keep tracks of what we are working on. So it should be easier than having a list of task into a single PR :).

I just don't know how to generate the net45 assemblies would you be able to update this PR with them ? And after that we merge this PR.

**Comment by ncave** [comment]
@MangelMaxime 
> I just don't know how to generate the net45 assemblies

You already have them [here](https://github.com/fable-compiler/fable-repl/tree/feature/new_repl/public/metadata), these should be good enough for now.

**Comment by MangelMaxime** [comment]
Ah yes that's true :) thanks you @ncave

**Comment by MangelMaxime** [comment]
For info, I am working on the last WIP feature before merging this PR.

And for me, speaking from a pure user experience point of view, I don't see a lot of differences between the old/new binaries. I didn't make any time performance measure yet.

**Comment by ncave** [comment]
@MangelMaxime If you use a bigger file, you'll see it right away, they [scale differently](https://github.com/fable-compiler/Fable/issues/1205) with size.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro I can't make `ExportDefault` works...

I commented it in this commit: https://github.com/fable-compiler/fable-repl/pull/8/commits/951996c1634816660f4da1e8c117bd30af76d529#diff-b5ce1565c2555faa5e0618ae5c1fcd3d

When, I try to do:
```fsharp
let editor : Fable.Editor.Interfaces.IExports = importDefault "editor"
console.log editor
```

I got `undefined`, can you please help me :) ?

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime Sorry, I don't understand. In the commit, `ExportDefault` is commented out.

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime You use `ExportDefault` [as in here](https://github.com/fable-compiler/Fable/blob/5333b3d53eae1ac56d6cd1a4c4042ea975a6c88c/src/dotnet/Fable.JS/Main.fs#L163-L164) (well, in that sample you could also put the attribute directly on top of `defaultManager`) then you import it [as in here](https://github.com/fable-compiler/fable-repl/blob/53195f8e041a2fcb8f4a63add7595378be4244a0/src/Monaco/Editor.fs#L16). Note the path must follow the rules for JS importing. In this case, if you want to use an alias instead of a relative path, you have to declare the alias [in the webpack config](https://github.com/fable-compiler/fable-repl/blob/feature/new_repl/webpack.config.js#L36) (note in this example the fable-repl is exposed as a global variable [as it is loaded directly by index.html](https://github.com/fable-compiler/fable-repl/blob/53195f8e041a2fcb8f4a63add7595378be4244a0/public/index.html#L15-L16)).

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro I will create a branch with the code uncommented. Because, i think I did what you said.

**Comment by ncave** [comment]
@MangelMaxime @alfonsogarciacaro 
Just in time for the holidays, some performance [improvements](https://github.com/fable-compiler/Fable/pull/1300) for the netcore binaries.

Happy Holidays and best wishes to you and your families!

**Comment by MangelMaxime** [comment]
Awesome @ncave , just in time for me to make the next version of the repl public :) Doing some clean up :)

Happy holidays and best wishes to you too. 🎅 🎁

**Comment by alfonsogarciacaro** [comment]
Fantastic @ncave :clap: 🥇 :clap:

Thanks a lot for all your work with Fable. I wish you a great and well-deserved holidays! Let's get new energies to make 2018 a great year for Fable! 💪

**Comment by MangelMaxime** [comment]
Here is my Christmas gift:

🎉 🍾 🎁 http://fable.io/fable-repl/ 🎁 🍾 🎉 

Thank to both of you for the help :) Still a lot of thing to do, but I will stop here for now :) I will create issue to track the next task I have in mind and so we will be able to keep track of it and work together when needed.

@alfonsogarciacaro If this is working for you too, I will let you make an public announcement with FableCompiler twitter if we want to make it public :) (Someone already liked the WIP PR ^^)

**Comment by ncave** [comment]
@MangelMaxime Awesome, thanks for merging into master. If any of the stale branches are no longer needed, they can be cleaned up.

**Comment by alfonsogarciacaro** [comment]
Absolutely awesome @MangelMaxime! ⭐️ ⭐️ You're a Fable superstar!! ⭐️ ⭐️ 

Applause

It's a bit late now so we better make the announcement tomorrow. Totally agreed, let's keep separated issues for minor improvements :+1:

**Comment by alfonsogarciacaro** [comment]
And [this is for you](https://whitetigle.github.io/fsharp_advent_2017/?name=ncave) @ncave!

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Yes, totally agree doing an announcement at 1 AM don't work well in general :)

**Pull request merged**
